#!/bin/bash

echo "================================================"
echo "🎯 STEP 2: Phocus 앱 BLE 통신 캡처 실행"
echo "================================================"
echo ""

echo "📱 사전 체크리스트:"
echo "✓ Console 앱이 열려있고 iPhone이 선택됨"
echo "✓ 필터가 설정됨 (bluetooth/phocus/hasselblad)"
echo "✓ 카메라 전원이 켜져있음"
echo "✓ iPhone에 Phocus 2 앱이 설치됨"
echo ""

echo "🔴 중요: 다음 순서를 정확히 따라주세요!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣ Console 준비"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Console 창 Clear (Cmd+K)"
echo "• 로그 기록 시작 (Action > Start Streaming)"
echo ""
read -p "준비되면 Enter..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣ Phocus 앱 실행"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• iPhone에서 Phocus 2 앱 실행"
echo "• 카메라 연결 화면으로 이동"
echo ""
read -p "앱이 실행되면 Enter..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣ 카메라 Bluetooth 연결"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• X2D II 선택하여 Bluetooth 연결"
echo "• 연결 성공 메시지 확인"
echo ""
echo "🔍 Console에서 찾을 패턴:"
echo "   - characteristic write"
echo "   - FFF0, FFF3, FFF4"
echo "   - hex 값 (0x...)"
echo ""
read -p "Bluetooth 연결되면 Enter..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣ WiFi 활성화 관찰"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Phocus 앱에서 WiFi 연결 시도"
echo "• iPhone WiFi 설정에서 SSID 확인"
echo ""
echo "🔍 중요 로그 포인트:"
echo "   - WiFi 활성화 명령"
echo "   - SSID 브로드캐스트 시작"
echo "   - 네트워크 구성 변경"
echo ""
read -p "WiFi가 보이면 Enter..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5️⃣ 로그 저장"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Console에서 Action > Pause"
echo "• File > Save... (Cmd+S)"
echo "• 파일명: phocus_ble_capture.log"
echo ""

# 로그 파일 위치
LOG_DIR="/Users/munkyo/works/ai-code/photo/PhotoPinMobile/logs"
mkdir -p "$LOG_DIR"

echo "💾 로그 파일 저장 위치:"
echo "   $LOG_DIR/phocus_ble_capture.log"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 캡처된 데이터 분석 포인트"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. BLE Service/Characteristic:"
echo "   - Service UUID (예: FFF0)"
echo "   - Characteristic UUIDs"
echo "   - Write/Notify 패턴"
echo ""
echo "2. 명령 시퀀스:"
echo "   - 초기화 명령"
echo "   - WiFi 활성화 명령"
echo "   - AP 모드 설정"
echo "   - SSID 브로드캐스트"
echo ""
echo "3. 타이밍:"
echo "   - 명령 간 딜레이"
echo "   - 응답 대기 시간"
echo ""

echo "✅ 캡처 완료!"
echo ""
echo "다음 단계:"
echo "1. 저장된 로그 파일 분석"
echo "2. BLE 명령 패턴 추출"
echo "3. 우리 앱에 적용"
echo ""
echo "분석을 시작하려면 다음 명령 실행:"
echo "   ./step3_analyze_capture.sh"